# Generated by Django 5.1.3 on 2024-12-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_stocktransaction_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='reference_number',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
    ]
